apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hack9-managed-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
        editor: vscode
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: "/data"
          name: volume
      - name: mcmon
        image: timh777/hack9-mcmon:v1
        env:
        - name: Message
          value: "Kube deployed"
        - name: ServerIp
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: ServerIp
        - name: WorkspaceId
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: WorkspaceId
        - name: ServerPort
          value: 25565
        - name: OmsSecret
          valueFrom:
            secretKeyRef:
              name: secrets
              key: omssecret2
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: hack9-managed-disk
---
apiVersion: v1
kind: Service
metadata:
  name: minecraftlb
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
  - name: rcon
    port: 25575
    targetPort: 25575

  selector:
    app: minecraft
