apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "minecraft.fullname" . }}
  labels:
    app: {{ template "minecraft.name" . }}
    chart: {{ template "minecraft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ServerIp: "minecraft5"
  ServerPort: "25565"
  WorkspaceId: "95603f05-cda8-430b-aa97-45fb3ad20395"
  Message: "Via Monitoring Sidecar"