apiVersion: v1
kind: Service
metadata:
  name: {{ template "minecraft.fullname" . }}
  labels:
    app: {{ template "minecraft.name" . }}
    chart: {{ template "minecraft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: minecraft
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  - name: rcon
    port: {{ .Values.service.adminPort }}
    targetPort: {{ .Values.service.adminPort }}
  selector:
    app: {{ template "minecraft.name" . }}
    release: {{ .Release.Name }}
