apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apicoreapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apicoreapp
        editor: vscode
    spec:
      containers:
      - name: apicoreapp
        image: muzzar78/apicoreapp
        ports:
        - containerPort: 80
          name: apicoreapp
---
apiVersion: v1
kind: Service
metadata:
  name: apicoreapplb
spec:
  type: LoadBalancer
  ports:
  - name: apicoreapp
    port: 80
    targetPort: 80
  selector:
    app: apicoreapp
