apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hack9-managed-disk{i}
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraft{i}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft{i}
        editor: vscode
    spec:
      containers:
      - name: minecraft{i}
        image: openhack/minecraft-server:2.0
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: "/data"
          name: volume
      - name: mcmon{i}
        image: timh777/hack9-mcmon:v1
        env:
        - name: Message
          value: "Kube deployed"
        - name: ServerIp
          value: "{ip}"
        - name: WorkspaceId
          value: "95603f05-cda8-430b-aa97-45fb3ad20395"
        - name: ServerPort
          value: "25565"
        - name: OmsSecret
          value: "dHJ3bVh0Vy9NMUloM0xEaCtiMUdjWG5hT0pUcTlLMzRHdHRUejQ1dXhPMzZkQ3kzS1Bka0g1WDhpdVV4eTNMck9OeCtWaXpmWHovZnowRHFmdkMwUUE9PQ=="
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: hack9-managed-disk{i}
---
apiVersion: v1
kind: Service
metadata:
  name: minecraftlb{i}
spec:
  type: LoadBalancer
  ports:
  - name: minecraft{i}
    port: 25565
    targetPort: 25565
  - name: rcon
    port: 25575
    targetPort: 25575
  selector:
    app: minecraft{i}
